# Generated by Django 2.2.3 on 2019-07-16 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('text', models.TextField()),
                ('expiry', models.CharField(max_length=5)),
                ('filename', models.CharField(max_length=150)),
            ],
        ),
    ]
